project_id = "vcfbvwnyxasntgpahnmh"

[functions.drug-lookup]
verify_jwt = false

[functions.insurance-lookup]
verify_jwt = false

[functions.provider-search]
verify_jwt = false

[functions.generate-report]
verify_jwt = false

